build: false

version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.4

init:
  - set CONDA=Miniconda
  - if "%PYTHON%" == "3.4" (set CONDA=%CONDA%3)
  - if "%PLATFORM%" == "x64" (set CONDA=%CONDA%-x64)
  - echo %CONDA%
  - set PATH=C:\%CONDA%;C:\%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - conda update conda
  - conda install numpy scipy nose hdf5 sphinx mock --quiet

install:
  - echo on
  #We need to run these two lines to have nmake available for doctests
  - cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
  - vcvarsall amd64
  #Return back to continue install of OpenMDAO
  - cd C:\projects\openmdao-w047s
  - pip install .

test_script:
  - nosetests
  #after tests, need to cd down so that conf.py can be found for doctest
  - cd openmdao/docs
  - nmake /f Makefile.nmake doctest
