build: false

version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.4

init:
  - "ECHO %PYTHON%"
  - conda config --set always_yes yes
  # We need to do this first as other commands may not work with older versions of conda.
  - conda update conda
  - conda install numpy scipy nose hdf5 --quiet

install:
  - pip install .

test_script:
  - nosetests
